apiVersion: v1
kind: Service
metadata:
  name: {{ include "pg.fullname" . }}
  labels:
    {{- include "pg.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
  selector:
    {{- include "pg.selectorLabels" . | nindent 4 }}
