{{- if .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sf.api.fullname" . }}
  labels:
    {{- include "sf.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "sf.selectorLabels" (dict "root" . "component" "api") | nindent 6 }}
{{- end }}
{{- if and .Values.web.enabled .Values.web.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sf.web.fullname" . }}
  labels:
    {{- include "sf.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  minAvailable: {{ .Values.web.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "sf.selectorLabels" (dict "root" . "component" "web") | nindent 6 }}
{{- end }}
{{- if .Values.worker.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sf.worker.fullname" . }}
  labels:
    {{- include "sf.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  minAvailable: {{ .Values.worker.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "sf.selectorLabels" (dict "root" . "component" "worker") | nindent 6 }}
{{- end }}
