{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sf.web.fullname" . }}
  labels:
    {{- include "sf.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.web.port }}
      targetPort: http
  selector:
    {{- include "sf.selectorLabels" (dict "root" . "component" "web") | nindent 4 }}
{{- end }}
